prometheus:
  prometheusSpec:
    retention: 15d
    nodeselector:
      kubernetes.io/hostname: monitoring
      role: monitoring
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m  

grafana:
  nodeSelector:
    kubernetes.io/hostname: monitoring
    role: monitoring
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi        
  adminpassword: "StrongPassword123"
  service:
    type: NodePort
    nodePort: 30090
    
alertmanager:
  alertmanagerSpec:
    nodeSelector: 
      role: monitoring
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi


additionalPrometheusRuleMap:
  custom-rules:
    groups:
      - name: custom-kubernetes-apps
        rules:
          - alert: kubePodCrashLoopingFast
            expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) >= 1
            for: 30s
            labels:
              severity: warning
            annotations:
              description: "Pod {{$labels.namespace}}/{{$labels.pod}} is in CrashLoopBackOff state for more than 30 seconds."
            

          - alert: kubePodCrashLoopingFast
            expr: max_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}) >= 1
            for: 10s
            labels:
              severity: warning
            annotations:
              description: "Pod {{$labels.namespace}}/{{$labels.pod}} is in OOMKilled state for more than 10 seconds."
            

          - alert: kubePodCrashLoopingFast
            expr: max_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}) == 1
            for: 10s
            labels:
              severity: warning
            annotations:
              description: "Pod {{$labels.namespace}}/{{$labels.pod}} container {{$labels.container}} was OOMKilled in the last 10 seconds."

          


            

